package com.yorkpiratesgame.io;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;

public enum TileType {

    SeaTile1(1, false, "Sea Tile"),
    SeaTile2(2, false, "Sea Tile"),
    SeaTile3(3, false, "Sea Tile"),
    SeaTile4(4, false, "Sea Tile"),
    SeaTile5(5, false, "Sea Tile"),
    SeaTile6(6, false, "Sea Tile"),
    SeaTile34(34, false, "Sea Tile"),
    SeaTile35(35, false, "Sea Tile"),
    SeaTile36(36, false, "Sea Tile"),
    SeaTile37(37, false, "Sea Tile"),
    SeaTile38(38, false, "Sea Tile"),
    SeaTile39(39, false, "Sea Tile"),
    SeaTile66(66, false, "Sea Tile"),
    SeaTile67( 67 , false, "Sea Tile"),
    SeaTile68( 68 , false, "Sea Tile"),
    SeaTile69( 69 , false, "Sea Tile"),
    SeaTile70( 70 , false, "Sea Tile"),
    SeaTile71( 71 , false, "Sea Tile"),
    SeaTile99( 99 , false, "Sea Tile"),
    SeaTile100( 100 , false, "Sea Tile"),
    SeaTile101( 101 , false, "Sea Tile"),
    SeaTile102( 102 , false, "Sea Tile"),
    SeaTile103( 103 , false, "Sea Tile"),
    SeaTile104( 104 , false, "Sea Tile"),
    SeaTile132( 132 , false, "Sea Tile"),
    SeaTile133( 133 , false, "Sea Tile"),
    SeaTile134( 134 , false, "Sea Tile"),
    SeaTile135( 135 , false, "Sea Tile"),
    SeaTile136( 136 , false, "Sea Tile"),
    SeaTile137( 137 , false, "Sea Tile"),
    SeaTile166( 166 , false, "Sea Tile"),
    SeaTile167( 167 , false, "Sea Tile"),
    SeaTile168( 168 , false, "Sea Tile"),
    SeaTile169( 169 , false, "Sea Tile"),
    SeaTile170( 170 , false, "Sea Tile"),
    SeaTile171( 171 , false, "Sea Tile"),
    smallIsland9( 9 , true, "Small Island"),
    smallIsland10( 10 , true, "Small Island"),
    smallIsland75( 75 , true, "Small Island"),
    smallIsland76( 76 , true, "Small Island"),
    smallIsland77( 77 , true, "Small Island"),
    smallIsland41( 41 , true, "Small Island"),
    smallIsland42( 42 , true, "Small Island"),
    smallIsland43( 43 , true, "Small Island"),
    smallIsland44( 44 , true, "Small Island"),
    smallIsland107( 107 , true, "Small Island"),
    smallIsland108( 108 , true, "Small Island"),
    smallIsland109( 109 , true, "Small Island"),
    smallIsland110( 110 , true, "Small Island"),
    smallIsland140( 140 , true, "Small Island"),
    smallIsland141( 141 , true, "Small Island"),
    smallIsland142( 142 , true, "Small Island"),
    smallIsland143( 143 , true, "Small Island"),
    goodrickeIsland243 ( 243 , true, "Goodricke College"),
    goodrickeIsland244 ( 244 , true, "Goodricke College"),
    goodrickeIsland275 ( 275 , true, "Goodricke College"),
    goodrickeIsland276 ( 276 , true, "Goodricke College"),
    goodrickeIsland277 ( 277 , true, "Goodricke College"),
    goodrickeIsland307 ( 307 , true, "Goodricke College"),
    goodrickeIsland308 ( 308 , true, "Goodricke College"),
    goodrickeIsland309 ( 309 , true, "Goodricke College"),
    goodrickeIsland310 ( 310 , true, "Goodricke College"),
    goodrickeIsland311 ( 311 , true, "Goodricke College"),
    goodrickeIsland312 ( 312 , true, "Goodricke College"),
    goodrickeIsland313 ( 313 , true, "Goodricke College"),
    goodrickeIsland340 ( 340 , true, "Goodricke College"),
    goodrickeIsland341 ( 341 , true, "Goodricke College"),
    goodrickeIsland342 ( 342 , true, "Goodricke College"),
    goodrickeIsland343 ( 343 , true, "Goodricke College"),
    goodrickeIsland344 ( 344 , true, "Goodricke College"),
    goodrickeIsland345 ( 345 , true, "Goodricke College"),
    goodrickeIsland346 ( 346 , true, "Goodricke College"),
    goodrickeIsland347 ( 347 , true, "Goodricke College"),
    goodrickeIsland374 ( 374 , true, "Goodricke College"),
    goodrickeIsland375 ( 375 , true, "Goodricke College"),
    goodrickeIsland376 ( 376 , true, "Goodricke College"),
    goodrickeIsland377 ( 377 , true, "Goodricke College"),
    goodrickeIsland378 ( 378 , true, "Goodricke College"),
    goodrickeIsland379 ( 379 , true, "Goodricke College"),
    goodrickeIsland380 ( 380 , true, "Goodricke College"),
    goodrickeIsland381 ( 381 , true, "Goodricke College"),
    goodrickeIsland407 ( 407 , true, "Goodricke College"),
    goodrickeIsland408 ( 408 , true, "Goodricke College"),
    goodrickeIsland409 ( 409 , true, "Goodricke College"),
    goodrickeIsland410 ( 410 , true, "Goodricke College"),
    goodrickeIsland411 ( 411 , true, "Goodricke College"),
    goodrickeIsland412 ( 412 , true, "Goodricke College"),
    goodrickeIsland413 ( 413 , true, "Goodricke College"),
    goodrickeIsland414 ( 414 , true, "Goodricke College"),
    goodrickeIsland415 ( 415 , true, "Goodricke College"),
    goodrickeIsland435 ( 435 , true, "Goodricke College"),
    goodrickeIsland436 ( 436 , true, "Goodricke College"),
    goodrickeIsland437 ( 437 , true, "Goodricke College"),
    goodrickeIsland438 ( 438 , true, "Goodricke College"),
    goodrickeIsland439 ( 439 , true, "Goodricke College"),
    goodrickeIsland440 ( 440 , true, "Goodricke College"),
    goodrickeIsland441 ( 441 , true, "Goodricke College"),
    goodrickeIsland442 ( 442 , true, "Goodricke College"),
    goodrickeIsland443 ( 443 , true, "Goodricke College"),
    goodrickeIsland444 ( 444 , true, "Goodricke College"),
    goodrickeIsland445 ( 445 , true, "Goodricke College"),
    goodrickeIsland446 ( 446 , true, "Goodricke College"),
    goodrickeIsland447 ( 447 , true, "Goodricke College"),
    goodrickeIsland448 ( 448 , true, "Goodricke College"),
    goodrickeIsland466 ( 466 , true, "Goodricke College"),
    goodrickeIsland467 ( 467 , true, "Goodricke College"),
    goodrickeIsland468 ( 468 , true, "Goodricke College"),
    goodrickeIsland469 ( 469 , true, "Goodricke College"),
    goodrickeIsland470 ( 470 , true, "Goodricke College"),
    goodrickeIsland471 ( 471 , true, "Goodricke College"),
    goodrickeIsland472 ( 472 , true, "Goodricke College"),
    goodrickeIsland473 ( 473 , true, "Goodricke College"),
    goodrickeIsland474 ( 474 , true, "Goodricke College"),
    goodrickeIsland475 ( 475 , true, "Goodricke College"),
    goodrickeIsland476 ( 476 , true, "Goodricke College"),
    goodrickeIsland477 ( 477 , true, "Goodricke College"),
    goodrickeIsland478 ( 478 , true, "Goodricke College"),
    goodrickeIsland479 ( 479 , true, "Goodricke College"),
    goodrickeIsland480 ( 480 , true, "Goodricke College"),
    goodrickeIsland481 ( 481 , true, "Goodricke College"),
    goodrickeIsland482 ( 482 , true, "Goodricke College"),
    goodrickeIsland498 ( 498 , true, "Goodricke College"),
    goodrickeIsland499 ( 499 , true, "Goodricke College"),
    goodrickeIsland500 ( 500 , true, "Goodricke College"),
    goodrickeIsland501 ( 501 , true, "Goodricke College"),
    goodrickeIsland502 ( 502 , true, "Goodricke College"),
    goodrickeIsland503 ( 503 , true, "Goodricke College"),
    goodrickeIsland504 ( 504 , true, "Goodricke College"),
    goodrickeIsland505 ( 505 , true, "Goodricke College"),
    goodrickeIsland506 ( 506 , true, "Goodricke College"),
    goodrickeIsland507 ( 507 , true, "Goodricke College"),
    goodrickeIsland508 ( 508 , true, "Goodricke College"),
    goodrickeIsland509 ( 509 , true, "Goodricke College"),
    goodrickeIsland510 ( 510 , true, "Goodricke College"),
    goodrickeIsland511 ( 511 , true, "Goodricke College"),
    goodrickeIsland512 ( 512 , true, "Goodricke College"),
    goodrickeIsland513 ( 513 , true, "Goodricke College"),
    goodrickeIsland514 ( 514 , true, "Goodricke College"),
    goodrickeIsland531 ( 531 , true, "Goodricke College"),
    goodrickeIsland532 ( 532 , true, "Goodricke College"),
    goodrickeIsland533 ( 533 , true, "Goodricke College"),
    goodrickeIsland534 ( 534 , true, "Goodricke College"),
    goodrickeIsland535 ( 535 , true, "Goodricke College"),
    goodrickeIsland536 ( 536 , true, "Goodricke College"),
    goodrickeIsland537 ( 537 , true, "Goodricke College"),
    goodrickeIsland538 ( 538 , true, "Goodricke College"),
    goodrickeIsland539 ( 539 , true, "Goodricke College"),
    goodrickeIsland540 ( 540 , true, "Goodricke College"),
    goodrickeIsland541 ( 541 , true, "Goodricke College"),
    goodrickeIsland542 ( 542 , true, "Goodricke College"),
    goodrickeIsland543 ( 543 , true, "Goodricke College"),
    goodrickeIsland544 ( 544 , true, "Goodricke College"),
    goodrickeIsland545 ( 545 , true, "Goodricke College"),
    goodrickeIsland546 ( 546 , true, "Goodricke College"),
    goodrickeIsland547 ( 547 , true, "Goodricke College"),
    goodrickeIsland563 ( 563 , true, "Goodricke College"),
    goodrickeIsland564 ( 564 , true, "Goodricke College"),
    goodrickeIsland565 ( 565 , true, "Goodricke College"),
    goodrickeIsland566 ( 566 , true, "Goodricke College"),
    goodrickeIsland567 ( 567 , true, "Goodricke College"),
    goodrickeIsland568 ( 568 , true, "Goodricke College"),
    goodrickeIsland569 ( 569 , true, "Goodricke College"),
    goodrickeIsland570 ( 570 , true, "Goodricke College"),
    goodrickeIsland571 ( 571 , true, "Goodricke College"),
    goodrickeIsland572 ( 572 , true, "Goodricke College"),
    goodrickeIsland573 ( 573 , true, "Goodricke College"),
    goodrickeIsland574 ( 574 , true, "Goodricke College"),
    goodrickeIsland575 ( 575 , true, "Goodricke College"),
    goodrickeIsland576 ( 576 , true, "Goodricke College"),
    goodrickeIsland577 ( 577 , true, "Goodricke College"),
    goodrickeIsland578 ( 578 , true, "Goodricke College"),
    goodrickeIsland579 ( 579 , true, "Goodricke College"),
    goodrickeIsland580 ( 580 , true, "Goodricke College"),
    goodrickeIsland596 ( 596 , true, "Goodricke College"),
    goodrickeIsland597 ( 597 , true, "Goodricke College"),
    goodrickeIsland598 ( 598 , true, "Goodricke College"),
    goodrickeIsland599 ( 599 , true, "Goodricke College"),
    goodrickeIsland600 ( 600 , true, "Goodricke College"),
    goodrickeIsland601 ( 601 , true, "Goodricke College"),
    goodrickeIsland602 ( 602 , true, "Goodricke College"),
    goodrickeIsland603 ( 603 , true, "Goodricke College"),
    goodrickeIsland604 ( 604 , true, "Goodricke College"),
    goodrickeIsland605 ( 605 , true, "Goodricke College"),
    goodrickeIsland606 ( 606 , true, "Goodricke College"),
    goodrickeIsland607 ( 607 , true, "Goodricke College"),
    goodrickeIsland608 ( 608 , true, "Goodricke College"),
    goodrickeIsland609 ( 609 , true, "Goodricke College"),
    goodrickeIsland610 ( 610 , true, "Goodricke College"),
    goodrickeIsland611 ( 611 , true, "Goodricke College"),
    goodrickeIsland612 ( 612 , true, "Goodricke College"),
    goodrickeIsland613 ( 613 , true, "Goodricke College"),
    goodrickeIsland614 ( 614 , true, "Goodricke College"),
    goodrickeIsland615 ( 615 , true, "Goodricke College"),
    goodrickeIsland629 ( 629 , true, "Goodricke College"),
    goodrickeIsland630 ( 630 , true, "Goodricke College"),
    goodrickeIsland631 ( 631 , true, "Goodricke College"),
    goodrickeIsland632 ( 632 , true, "Goodricke College"),
    goodrickeIsland633 ( 633 , true, "Goodricke College"),
    goodrickeIsland634 ( 634 , true, "Goodricke College"),
    goodrickeIsland635 ( 635 , true, "Goodricke College"),
    goodrickeIsland636 ( 636 , true, "Goodricke College"),
    goodrickeIsland637 ( 637 , true, "Goodricke College"),
    goodrickeIsland638 ( 638 , true, "Goodricke College"),
    goodrickeIsland639 ( 639 , true, "Goodricke College"),
    goodrickeIsland640 ( 640 , true, "Goodricke College"),
    goodrickeIsland641 ( 641 , true, "Goodricke College"),
    goodrickeIsland642 ( 642 , true, "Goodricke College"),
    goodrickeIsland643 ( 643 , true, "Goodricke College"),
    goodrickeIsland644 ( 644 , true, "Goodricke College"),
    goodrickeIsland645 ( 645 , true, "Goodricke College"),
    goodrickeIsland646 ( 646 , true, "Goodricke College"),
    goodrickeIsland647 ( 647 , true, "Goodricke College"),
    goodrickeIsland648 ( 648 , true, "Goodricke College"),
    goodrickeIsland662 ( 662 , true, "Goodricke College"),
    goodrickeIsland663 ( 663 , true, "Goodricke College"),
    goodrickeIsland664 ( 664 , true, "Goodricke College"),
    goodrickeIsland665 ( 665 , true, "Goodricke College"),
    goodrickeIsland666 ( 666 , true, "Goodricke College"),
    goodrickeIsland667 ( 667 , true, "Goodricke College"),
    goodrickeIsland668 ( 668 , true, "Goodricke College"),
    goodrickeIsland669 ( 669 , true, "Goodricke College"),
    goodrickeIsland670 ( 670 , true, "Goodricke College"),
    goodrickeIsland671 ( 671 , true, "Goodricke College"),
    goodrickeIsland672 ( 672 , true, "Goodricke College"),
    goodrickeIsland673 ( 673 , true, "Goodricke College"),
    goodrickeIsland674 ( 674 , true, "Goodricke College"),
    goodrickeIsland675 ( 675 , true, "Goodricke College"),
    goodrickeIsland676 ( 676 , true, "Goodricke College"),
    goodrickeIsland677 ( 677 , true, "Goodricke College"),
    goodrickeIsland678 ( 678 , true, "Goodricke College"),
    goodrickeIsland679 ( 679 , true, "Goodricke College"),
    goodrickeIsland680 ( 680 , true, "Goodricke College"),
    goodrickeIsland681 ( 681 , true, "Goodricke College"),
    goodrickeIsland695 ( 695 , true, "Goodricke College"),
    goodrickeIsland696 ( 696 , true, "Goodricke College"),
    goodrickeIsland697 ( 697 , true, "Goodricke College"),
    goodrickeIsland698 ( 698 , true, "Goodricke College"),
    goodrickeIsland699 ( 699 , true, "Goodricke College"),
    goodrickeIsland700 ( 700 , true, "Goodricke College"),
    goodrickeIsland701 ( 701 , true, "Goodricke College"),
    goodrickeIsland702 ( 702 , true, "Goodricke College"),
    goodrickeIsland703 ( 703 , true, "Goodricke College"),
    goodrickeIsland704 ( 704 , true, "Goodricke College"),
    goodrickeIsland705 ( 705 , true, "Goodricke College"),
    goodrickeIsland706 ( 706 , true, "Goodricke College"),
    goodrickeIsland707 ( 707 , true, "Goodricke College"),
    goodrickeIsland708 ( 708 , true, "Goodricke College"),
    goodrickeIsland709 ( 709 , true, "Goodricke College"),
    goodrickeIsland710 ( 710 , true, "Goodricke College"),
    goodrickeIsland711 ( 711 , true, "Goodricke College"),
    goodrickeIsland712 ( 712 , true, "Goodricke College"),
    goodrickeIsland713 ( 713 , true, "Goodricke College"),
    goodrickeIsland714 ( 714 , true, "Goodricke College"),
    goodrickeIsland729 ( 729 , true, "Goodricke College"),
    goodrickeIsland730 ( 730 , true, "Goodricke College"),
    goodrickeIsland731 ( 731 , true, "Goodricke College"),
    goodrickeIsland732 ( 732 , true, "Goodricke College"),
    goodrickeIsland733 ( 733 , true, "Goodricke College"),
    goodrickeIsland734 ( 734 , true, "Goodricke College"),
    goodrickeIsland735 ( 735 , true, "Goodricke College"),
    goodrickeIsland736 ( 736 , true, "Goodricke College"),
    goodrickeIsland737 ( 737 , true, "Goodricke College"),
    goodrickeIsland738 ( 738 , true, "Goodricke College"),
    goodrickeIsland739 ( 739 , true, "Goodricke College"),
    goodrickeIsland740 ( 740 , true, "Goodricke College"),
    goodrickeIsland741 ( 741 , true, "Goodricke College"),
    goodrickeIsland742 ( 742 , true, "Goodricke College"),
    goodrickeIsland743 ( 743 , true, "Goodricke College"),
    goodrickeIsland744 ( 744 , true, "Goodricke College"),
    goodrickeIsland745 ( 745 , true, "Goodricke College"),
    goodrickeIsland746 ( 746 , true, "Goodricke College"),
    goodrickeIsland747 ( 747 , true, "Goodricke College"),
    goodrickeIsland762 ( 762 , true, "Goodricke College"),
    goodrickeIsland763 ( 763 , true, "Goodricke College"),
    goodrickeIsland764 ( 764 , true, "Goodricke College"),
    goodrickeIsland765 ( 765 , true, "Goodricke College"),
    goodrickeIsland766 ( 766 , true, "Goodricke College"),
    goodrickeIsland767 ( 767 , true, "Goodricke College"),
    goodrickeIsland768 ( 768 , true, "Goodricke College"),
    goodrickeIsland769 ( 769 , true, "Goodricke College"),
    goodrickeIsland770 ( 770 , true, "Goodricke College"),
    goodrickeIsland771 ( 771 , true, "Goodricke College"),
    goodrickeIsland772 ( 772 , true, "Goodricke College"),
    goodrickeIsland773 ( 773 , true, "Goodricke College"),
    goodrickeIsland774 ( 774 , true, "Goodricke College"),
    goodrickeIsland775 ( 775 , true, "Goodricke College"),
    goodrickeIsland776 ( 776 , true, "Goodricke College"),
    goodrickeIsland777 ( 777 , true, "Goodricke College"),
    goodrickeIsland778 ( 778 , true, "Goodricke College"),
    goodrickeIsland779 ( 779 , true, "Goodricke College"),
    goodrickeIsland780 ( 780 , true, "Goodricke College"),
    goodrickeIsland796 ( 796 , true, "Goodricke College"),
    goodrickeIsland797 ( 797 , true, "Goodricke College"),
    goodrickeIsland798 ( 798 , true, "Goodricke College"),
    goodrickeIsland799 ( 799 , true, "Goodricke College"),
    goodrickeIsland800 ( 800 , true, "Goodricke College"),
    goodrickeIsland801 ( 801 , true, "Goodricke College"),
    goodrickeIsland802 ( 802 , true, "Goodricke College"),
    goodrickeIsland803 ( 803 , true, "Goodricke College"),
    goodrickeIsland804 ( 804 , true, "Goodricke College"),
    goodrickeIsland805 ( 805 , true, "Goodricke College"),
    goodrickeIsland806 ( 806 , true, "Goodricke College"),
    goodrickeIsland807 ( 807 , true, "Goodricke College"),
    goodrickeIsland808 ( 808 , true, "Goodricke College"),
    goodrickeIsland809 ( 809 , true, "Goodricke College"),
    goodrickeIsland810 ( 810 , true, "Goodricke College"),
    goodrickeIsland811 ( 811 , true, "Goodricke College"),
    goodrickeIsland812 ( 812 , true, "Goodricke College"),
    goodrickeIsland830 ( 830 , true, "Goodricke College"),
    goodrickeIsland831 ( 831 , true, "Goodricke College"),
    goodrickeIsland832 ( 832 , true, "Goodricke College"),
    goodrickeIsland833 ( 833 , true, "Goodricke College"),
    goodrickeIsland834 ( 834 , true, "Goodricke College"),
    goodrickeIsland835 ( 835 , true, "Goodricke College"),
    goodrickeIsland836 ( 836 , true, "Goodricke College"),
    goodrickeIsland837 ( 837 , true, "Goodricke College"),
    goodrickeIsland838 ( 838 , true, "Goodricke College"),
    goodrickeIsland839 ( 839 , true, "Goodricke College"),
    goodrickeIsland840 ( 840 , true, "Goodricke College"),
    goodrickeIsland841 ( 841 , true, "Goodricke College"),
    goodrickeIsland842 ( 842 , true, "Goodricke College"),
    goodrickeIsland843 ( 843 , true, "Goodricke College"),
    goodrickeIsland844 ( 844 , true, "Goodricke College"),
    goodrickeIsland845 ( 845 , true, "Goodricke College"),
    goodrickeIsland871 ( 871 , true, "Goodricke College"),
    goodrickeIsland872 ( 872 , true, "Goodricke College"),
    goodrickeIsland873 ( 873 , true, "Goodricke College"),
    goodrickeIsland874 ( 874 , true, "Goodricke College"),
    goodrickeIsland875 ( 875 , true, "Goodricke College"),
    goodrickeIsland876 ( 876 , true, "Goodricke College"),
    goodrickeIsland877 ( 877 , true, "Goodricke College");

    public static final int TILE_SIZE = 24;

    private int id;
    private boolean collidable;
    private String name;
    private float damage;

    private TileType (int id, boolean collidable, String name){
            this(id, collidable, name, 0);
    }

    private TileType (int id, boolean collidable, String name, float damage){
        this.id = id;
        this.collidable = collidable;
        this.name = name;
        this.damage = damage;
    }

    public int getId(){return id;}
    public boolean isCollidable(){return collidable;}
    public String getName(){return name;}
    public float getDamage(){return damage;}

    private static HashMap<Integer, TileType> tileMap;

    static{
        tileMap = new HashMap<Integer, TileType>();
        for(TileType tileType : TileType.values()){
            tileMap.put(tileType.getId(), tileType);
        }
    }

    public static TileType getTileTypeById(int id){
        return tileMap.get(id);
    }
}
